namespace NUnitMigrator.Replacements;

// Replacement patterns (mostyl generated by ChatGPT and corrected)
internal static partial class ReplacementPatterns
{
    internal static Dictionary<string, string> Items => 
        AssertDirectItems
            .Concat(AssertThatIsItems)
            .Concat(AssertThatIsNotItems)
            .ToDictionary();

    internal static Dictionary<string, string> AssertDirectItems = new()
    {
        // Assert(object, object)
        { @"Assert\.AreEqual\((.+),\s*(.+)\);", "$2.Should().Be($1);" },
        { @"Assert\.AreNotEqual\((.+),\s*(.+)\);", "$2.Should().NotBe($1);" },
        { @"Assert\.IsTrue\((.+)\);", "$1.Should().BeTrue();" },
        { @"Assert\.IsFalse\((.+)\);", "$1.Should().BeFalse();" },
        { @"Assert\.IsNull\((.+)\);", "$1.Should().BeNull();" },
        { @"Assert\.NotNull\((.+)\);", "$1.Should().NotBeNull();" },
      
        // Assert.That(object, Has.*)
        { @"Assert\.That\((.+),\s*Has\.Exactly\((\d+)\)\.Matches<(.+)>\((.+)\)\);", "$1.Where($4).Should().HaveCount($2);" },
        { @"Assert\.That\((.+),\s*Has\.One\.Matches<(.+)>\((.+)\)\);", "$1.Should().ContainSingle($3);" },
        { @"Assert\.That\((.+),\s*Has\.None\.Matches<(.+)>\((.+)\)\);", "$1.Should().NotContain($3);" },
        { @"Assert\.That\(\s*(.+?)\s*\);", "$1.Should().BeTrue();" },

        // Assert.Throws<TException>(Expression)
        { @"Assert\.Throws<(.+)>\(\(\)\s*=>\s*(.+)\);", "Action act = () => $2;\nact.Should().Throw<$1>();" },
    };
}
